apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-hs8l
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-hs8l
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-hs8l
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-hs8l
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-hs8l
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hepz-tenant/rhtap-demo-app/hacbs-test-project-hs8l@sha256:e213450339771d8789a9d05b83d448635ab34c83cabff6d0e5968c6e0b220681
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
