apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-hs8l
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hepz-tenant/rhtap-demo-app/hacbs-test-project-hs8l@sha256:f06bd14303e6f9fa2d7255b9ee0d9b355aeac8fc55d07869ff7a10cb0af5615e
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
